'use client'
import React from 'react'
import './globals.css'
import type { Metadata } from 'next'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

export const metadata: Metadata = {
  title: 'Remind-MME',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode,
}) {
  const queryClient = new QueryClient()

  return (
      <html lang="en">
        <QueryClientProvider client={queryClient}>
          <body>
            {children}
            <ReactQueryDevtools />
          </body>
        </QueryClientProvider>
      </html>
  )
}
